name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install huggingface-hub
        run: pip install huggingface-hub

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          huggingface-cli repo create mentor-llm --type=space --yes || true
          git config --global user.email "mentor@llm.com"
          git config --global user.name "Mentor LLM Bot"
          git remote remove space || true
          git remote add space https://Evandro-Saints:${HF_TOKEN}@huggingface.co/spaces/Evandro-Saints/mentor-llm
          git push space main --force
