name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git remote add space https://Evandro-Saints:${HF_TOKEN}@huggingface.co/spaces/Evandro-Saints/mentor-llm
          git push space main --force
