name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Push to Hugging Face Spaces
        uses: huggingface/huggingface-cli-action@v0.1
        with:
          hf_token: ${{ secrets.HF_TOKEN }}
          repo_id: evandro-saints/mentor-llm
          repo_type: space
