name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main  # ou a branch que você estiver usando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install huggingface_hub
        run: |
          pip install huggingface_hub

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git remote add hf https://evandro-saints:${HF_TOKEN}@huggingface.co/spaces/evandro-saints/mentor-llm
          git push hf main --force
